config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'account', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get 'account/logout', to: 'devise/sessions#destroy'
    get 'account/setting', to: 'devise/registrations#edit'
  end
  root to:'home#index'

  get 'account/key', to: 'account#key'
  get 'index', to: 'home#index'
  get '/', to: 'home#index'

  resources :languages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord

  has_many :iterations
  belongs_to :problem
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/iteration.rb
class Iteration < ApplicationRecord
  belongs_to  :assignment
  has_many :comments
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :problems
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :language
  has_many :assignments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :assignments
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_filter :authenticate_user!
  def key
    render 'account/key'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'home/home'
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @languages = Language.all

    render 'languages/index'
  end


  def show
    @language = Language.find_by_id(params[:id])

    render 'languages/show'
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/home/home.html.erb
<div id="home">
  <section class="main">
    <section>
      <div class="home-top">
        <div class="container">
          <section class="contain-centered">
            <h1 class="logo">Practice</h1>
            <h3 class="slogan">通过代码练习，交流，提升编程技巧</h3>
          </section>
        </div>
      </div>
    </section>
  </section>

  <section>
    <div class="summary">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>
              <i class="fa fa-code"></i>
              下载代码练习到你到电脑，解决并运行代码
            </p>
            <p>
              <i class="fa fa-comment"></i>
              提交解决方案，查看Feedback，并和其他人交流如何优化代码
            </p>
            <p>
              <i class="fa fa-heart"></i>
              适合初学者和想要提高编程技巧到人
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <div class="container">
    <section class="content-primary">

      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
          <h2>你是代码菜鸟吗？</h2>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <p class="feelz">
            One moment you feel like you're getting it.
            The next moment you're stuck.
          </p>
        </div>
        <div class="col-md-8">
          <p>
            学习编程是一件很有挑战到事情...
            而且有时候枯燥，乏味，缺乏动力
          </p>

          <p>
            Practice 提供了小而精到编程练习，让你能够在解决问题到同时，学习到编程相关到知识，并且获得到满足感让你更加有动力继续前行！
          </p>

          <p>
            我们到Reviewer会查看你到解决方案，并且给出建议，让你了解到目前代码到问题，例如如何更好到组织代码，使用更恰当到API， 优化建议等等。
            这些都能够帮助你进一步理解和学习编程，比起单独学习，这种方式更加有效果！
          </p>
          <p class="cta">
            <a href="#" class="btn btn-lg btn-block cta-btn">write code like it's prose →</a>
          </p>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
          <h2>想学一门新到编程语言吗？</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <p class="feelz">
            You know what it’s like to be fluent.
            Suddenly you’re feeling incompetent and clumsy.
          </p>
        </div>
        <div class="col-md-8">
          <p>
            学一门新到编程语言不是一件轻松舒服到事情。
          </p>

          <p>
            You’re used to being productive.
            Now you feel hamstrung with one hand tied behind your back and an unfair suspicion that you should already know this.
          </p>

          <p>
            There's a gap when you're past the basics but real-world problems leave you swamped by details and wandering down rabbit holes.
            Exercism aims to fill that gap with lots of small, self-contained practice problems with just enough complexity to stretch your mind around new concepts.
          </p>

          <p>
            Your solutions are the starting point for a conversation centered around style, idioms, and best practices.
            You can write FORTRAN in any language, as the saying famously goes, but with enough feedback, you’ll quickly find yourself writing the language the way it wants to be written.
          </p>

          <p class="cta">
            <a href="#" class="btn btn-lg btn-block cta-btn">become fluent in a new language →</a>
          </p>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
          <h2>想写出更优雅，更高效到代码吗？</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <p class="feelz">
            Haphazard, convoluted code is infuriating, not to mention costly.
            That slapdash explosion of complexity is an expensive yak shave waiting to happen.
          </p>
        </div>
        <div class="col-md-8">
          <p>
            There's an art and a science to transforming unmaintainable code into elegant simplicity.
            It takes practice, experimentation, and deep thought.
          </p>

          <p>
            Exercism's tiny toy problems, in the form of automated tests, provide a balance of constraints and freedom.
            The exercises encourage you to explore trade-offs and best-practices.
          </p>

          <p>
            Each solution you write is an occasion to ponder readability and code smells.
            Each solution you review challenges you to articulate your experiences and gut feelings.
            Each discussion is an opportunity to strengthen your instincts for clean, well-factored code.
          </p>

          <p class="cta">
            <a href="#" class="btn btn-lg btn-block cta-btn">master the art of clean code →</a>
          </p>
        </div>
      </div>
    </section>
  </div>
  <div class="container">
  </div>
</div>

app/views/languages/index.html.erb
<div class="container">
  <section>
    <h2>目前提供到编程语言：</h2>
    <hr/>
  </section>

  <section class="row">

    <% @languages.each do |language|%>
    <div class="col-sm-6 col-md-4 col-lg-3 ">
      <div class="thumbnail" style="height: 360px;">
        <a href="#" title="<%= language.name %>"><img class="lazy" src="http://static.bootcss.com/www/assets/img/codeguide.png" width="300" height="150"></a>
        <div class="caption">
          <h3>
            <a class="redLink" href="<%= language_path(language)%>" title="<%= language.desc %>"><%= language.name %><br></a>
          </h3>
          <p>
            <%= language.desc %>
          </p>
        </div>
      </div>
    </div>
    <% end %>

  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice -- Learn to code more happy !</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navigator' %>
    <main role="main">
      <% if notice %>
        <div id="alert" class="alert alert-info navbar-fixed-top" role="alert"><%= notice %></div>
      <% elsif alert %>
        <div id="alert" class="alert alert-warning navbar-fixed-top" role="alert"><%= alert %></div>
      <% end%>
      <%= yield %>
    </main>
    <%= render partial: 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer id="footer" role="contentinfo">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 col-md-2">
        <p><a class="wordmark" href="/">Home</a></p>
        <p><a href="/contact">联系我们</a></p>
        <p><a href="/about">关于</a></p>
        <p><a href="/join">加入我们</a></p>
      </div>
      <div class="col-sm-3 col-md-3">
        <p><a href="/help">Help</a></p>
        <p><a href="/teams/about">Teams</a></p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6 text-right footer-social">
        <ul class="list-inline">
          <li>
            <a href="#">
              <i class="fa fa-github fa-lg"></i>
              GitHub
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-twitter fa-lg"></i>
              Twitter
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-envelope"></i>
              Newsletter
            </a>
          </li>
        </ul>
        <br>
        <p class="text-muted small">
          © 2016 Han Lin
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navigator.html.erb
<nav class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" id="brand">&nbsp;</a>
      <a class="navbar-brand" href="/">Practice</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
            <li><a href="/dashboard">面板</a></li>
        <% end %>
        <li><a href="/languages">语言</a></li>
        <li><a href="/donate">赞助</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><a href="/inbox">消息</a></li>
            <li><a role="menuitem" tabindex="-1" href="/notifications"><i class="fa fa-bell"></i></a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" id="drop-account" href="#" data-toggle="dropdown">
                <img alt="" src="https://avatars.githubusercontent.com/u/3804365?s=20" width="20" height="20">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a role="menuitem" tabindex="-1" href="<%= account_setting_path%>">账户</a></li>
                <li><a role="menuitem" tabindex="-1" href="<%= account_key_path%>">API Key</a></li>
                <li><a role="menuitem" tabindex="-1" href="/looks">已查看</a></li>
                <li><a role="menuitem" tabindex="-1" href="<%= destroy_user_session_path %>">退出</a></li>
              </ul>
            </li>
        <% else %>
            <li><a href="/account/login">登录</a></li>
            <li><a href="/account/register/sign_up">注册</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>